### ISSUE TITLE
Add support for label descriptions

### ISSUE THREAD

**Issue by themightychris** [thommay/repo_man#5]
[Updating descriptions](https://developer.github.com/v3/issues/labels/#update-a-label) seems to be a standard part of the GitHub API now.

Can support be added to `repo_man` now for setting descriptions for managed labels?

**Comment by tas50** [comment]
It's on my list of things to do. I'd like to get descriptions added to all of ours since they're not all entirely obvious at first glance.

**Comment by themightychris** [comment]
@tas50 thanks for the quick reply, I started to try taking a stab at it myself but octokit.rb still seems to not support the description field: octokit/octokit.rb#1057

**Comment by themightychris** [comment]
Looks like descriptions is still part of a preview API :-(

I started tinkering with some node that gets descriptions into toml: https://github.com/thommay/repo_man/compare/master...themightychris:nodejs?expand=1

But I'm probably not going to finish it any time soon, doesn't seem productive to fork the project just because I don't know how to make octokit.rb use preview APIs

**Comment by tas50** [comment]
I just merged in support for label descriptions. It turns out you could pass them as an option.
